/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package data.set.explorer.ui;
import data.set.explorer.model.*;
/**
 *
 * @author daviddoherty
 */
public class Statistics extends javax.swing.JPanel {

	/**
	 * Creates new form Statistics
	 */
	public Statistics() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                StatisticsScrollPanel = new javax.swing.JScrollPane();
                StatisticsTextPane = new javax.swing.JTextPane();

                StatisticsScrollPanel.setViewportView(StatisticsTextPane);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(StatisticsScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(245, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(StatisticsScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(82, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

	public void setStatistics(DatasetTableModel datasetModelTable) {

        int count = datasetModelTable.getRowCount();
        double totalValue = 0;
        double totalFee = 0;

        for (int i = 0; i < count; i++) {
            Transaction t = datasetModelTable.getTransactionAt(i);
            totalValue += t.getValue();
            totalFee += t.getFee();
        }

        String stats = "---- Portfolio Statistics ----\n"
                     + "Total Transactions: " + count + "\n"
                     + "Total Value: " + totalValue + "\n"
                     + "Total Fees: " + totalFee + "\n";

        StatisticsTextPane.setText(stats);
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JScrollPane StatisticsScrollPanel;
        private javax.swing.JTextPane StatisticsTextPane;
        // End of variables declaration//GEN-END:variables
}
