package data.set.explorer.ui;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author daviddoherty
 */

import data.set.explorer.io.*;


public class TransactionTable extends javax.swing.JPanel {

	/**
	 * Creates new form TransactionTable
	 */
	private DatasetTableModel datasetTableModel;

	public TransactionTable() {
		initComponents();
	}
	
	public void setModel(DatasetTableModel model) {
		this.datasetTableModel = model;
		transactionsTable.setModel(this.datasetTableModel);
           // attach model
    }

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jScrollPane1 = new javax.swing.JScrollPane();
                transactionsTable = new javax.swing.JTable();
                DeleteRowButton = new javax.swing.JButton();
                openAddRowDialogButton = new javax.swing.JButton();
                saveButton = new javax.swing.JButton();

                transactionsTable.setModel(transactionsTable.getModel());
                transactionsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                jScrollPane1.setViewportView(transactionsTable);

                DeleteRowButton.setText("Delete");
                DeleteRowButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                DeleteRowButtonClicked(evt);
                        }
                });

                openAddRowDialogButton.setText("Add");
                openAddRowDialogButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                addRowButtonClicked(evt);
                        }
                });

                saveButton.setText("Save");
                saveButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                saveButtonPressed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(DeleteRowButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(openAddRowDialogButton, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(saveButton))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(openAddRowDialogButton)
                                .addGap(18, 18, 18)
                                .addComponent(DeleteRowButton)
                                .addGap(18, 18, 18)
                                .addComponent(saveButton)
                                .addContainerGap(110, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void addRowButtonClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRowButtonClicked
		// TODO add your handling code here:
		AddRowDialog addRowDialog = new AddRowDialog(null, true, this.datasetTableModel);
		addRowDialog.setVisible(true);
        }//GEN-LAST:event_addRowButtonClicked

        private void DeleteRowButtonClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRowButtonClicked
		// TODO add your handling code here:
        }//GEN-LAST:event_DeleteRowButtonClicked

        private void saveButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonPressed
		// TODO add your handling code here:
		DataSaver dataSaver = new DataSaver("/Users/daviddoherty/TUD/2nd Year/OOPs/Data Set Explorer/Doherty_David.txt");
		dataSaver.saveToTxt(this.datasetTableModel.getAllTransactions());
        }//GEN-LAST:event_saveButtonPressed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton DeleteRowButton;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JButton openAddRowDialogButton;
        private javax.swing.JButton saveButton;
        private javax.swing.JTable transactionsTable;
        // End of variables declaration//GEN-END:variables
}
