package data.set.explorer.ui;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author daviddoherty
 */


public class TransactionTable extends javax.swing.JPanel {

	/**
	 * Creates new form TransactionTable
	 */
	private DatasetTableModel tableModel;

	public TransactionTable() {
		initComponents();
		//tableModel = new DatasetTableModel();
		//jTable1.setModel(tableModel);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jScrollPane1 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                jButton1 = new javax.swing.JButton();
                jButton2 = new javax.swing.JButton();
                jButton3 = new javax.swing.JButton();

                jTable1.setModel(new DatasetTableModel().getAllTransactions());
                jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                jScrollPane1.setViewportView(jTable1);

                jButton1.setText("Delete");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                DeleteRowButtonClicked(evt);
                        }
                });

                jButton2.setText("Add");
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                addRowButtonClicked(evt);
                        }
                });

                jButton3.setText("Save");
                jButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                saveButtonPressed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(jButton3))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addContainerGap(110, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void addRowButtonClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRowButtonClicked
		// TODO add your handling code here:
		AddRowDialog addRowDialog = new AddRowDialog(null, true, this.tableModel);
		addRowDialog.setVisible(true);
        }//GEN-LAST:event_addRowButtonClicked

        private void DeleteRowButtonClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRowButtonClicked
		// TODO add your handling code here:
        }//GEN-LAST:event_DeleteRowButtonClicked

        private void saveButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonPressed
		// TODO add your handling code here:
        }//GEN-LAST:event_saveButtonPressed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton3;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable jTable1;
        // End of variables declaration//GEN-END:variables
}
